# def fullname(firstname,lastname):
#     print("Your fullname is " + firstname + "," + lastname)
# fullname("yetunde", "olanrewaju")

# firstname = input("enter your firstname:  ")
# lastname = input("enter your lastname: ")
# def fullname(firstname,lastname):
#     print("Your fullname is " + firstname + "," + lastname)
# fullname(firstname,lastname)

# x = int(input('enter a num: '))
# y = int(input('enter the 2nd num: '))
# def num(x,y):
#     ansa = x * y
#     print(ansa)
# num(x,y)
# def my_country(name= "Nigeria"):
#     country = "I am from " + name
#     return country
    

# print(my_country('italy'))
    
# # TO PASS A DEFAULT VALUE

# x = list(map(int,input("Enter three numbers:").split()))
# def duplicate(x):
#     y = []
#     for i in x:
#         new = i * 2
#         y.append(new)
#     return y
# print(duplicate(x)) 

import string


# write a function that returns the length of a string, the string
# should be a users input
# hi = input("Enter any word: ")
# def word():
#     print(len(hi))
# word()

# write a function that returns the max number in x, x should be a list
# x = list(map(int,input("Enter three numbers:").split()))
# def find_maximum (x):
#     ans = max(x)
#     return ans
# write a function that returns the min number in x, x should be a list
# x = list(map(int,input("Enter three numbers:").split()))
# def find_minimum (x):
#     ans = min(x)
#     print(ans)
#     # return ans
# find_minimum(x)

# x = 40
# def match(x):
#     y = x+50
#     # return y
#     print(y)
# match(x)

# def names():
#     names = "justice", "dominion", "yetunde"
#     print("hello" + " "  +   names[1])
# names()
#         OR
# def fun_name(*kids):
#     print("The youngest child is" + " " + kids[1])
# fun_name("justice", "dominion", "yetunde")

# def fruit_list(fruit1,fruit2):
#     print("My favourite is" + " " + fruit2)
# fruit_list(fruit1 = "pawpaw", fruit2 = "apple") 

# def world(**country):
#     print(country["east"] + " " + "is a country in Africa")
# world(south = "South Africa", east = "Kenya") 
    # DEFAULT ARGUMENT
# def my_car(car = "bmw"):
#     print(car)
# my_car() 
# write a function called addition, takes in 2 parameters and
# return there sum
# def addition(x,y):
#     ansa = x + y
#     print(ansa)
# addition(2,5)


# def print_lyrics():
#     print("I'm a lumberjack, and i am i'm okay.")
#     print("I sleep all night and i work all day.")
# print_lyrics()

# def greet(name):
#     # print(f"Hello {name} , goodmorning")
#     return(f"Hello {name} , goodmorning")
# print(greet("yinka"))

# def multiplication(x,y,z):
#     ansa = x*y*z
#     return(ansa)
# print(multiplication(2,3,4))

# def division(x,y):
#     ansa = x/y
#     return(ansa)
# print(division(2,3))


# NESTED FUNCTIONS
# def print_lyrics():
#     print("I am a boy")
# print_lyrics()

# def Repeat_lyrics():
#     print_lyrics()
# Repeat_lyrics()

# # DEFAULT ARGUEMENT
# def origin(country = "Nigeria"):
#     return(f"You are from {country}")
# print(origin("Turkey"))

# ARBITRARY ARGUMENTS
# def func_one(*name):
#     print(f"Hello  {name[1]}")
# func_one("ola", "tolu", "ade")

# create a variable that ask a user for a name, pass the variable into a 
# function that will say(hello obi)

# ques = input("Enter a name: ")
# def ansa(ques):
#     return(f"Hello {ques}")
# print(ansa(ques))

# write a code that accept hours and rate as input from a user and
# returns the salary
# ques1 = eval(input("Enter the work hour: "))
# quest2 = eval(input("Enter the rate: "))
# def salary(ques1,quest2):
#     ansa = ques1*quest2
#     return(ansa)
# print(salary(ques1,quest2))






    








    




    

